Controllers/ProductsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.Logging;
using Newtonsoft.Json;
using XuanThuLab.Data;
using XuanThuLab.Models;

namespace XuanThuLab.Controllers {

    public class ProductsController : Controller {
        private readonly AppDbContext _context;
        private readonly ILogger<ProductsController> _logger;

        public ProductsController(AppDbContext context, ILogger<ProductsController> logger) {
            _context = context;
            _logger = logger;
        }

        // Hiện thị danh sách sản phẩm, có nút chọn đưa vào giỏ hàng
        // GET: Products
        public IActionResult Index() {
            var products = _context.Products.ToList();
            return View(products);
        }

        /// xóa item trong cart
        [Route("/removecart/{productid:int}", Name = "removecart")]
        public IActionResult RemoveCart([FromRoute] int productid) {
            var cart = GetCartItems();
            var cartitem = cart.Find(p => p.Product.ProductId == productid);
            if(cartitem != null) {
                // Đã tồn tại, tăng thêm 1
                cart.Remove(cartitem);
            }

            SaveCartSession(cart);
            return RedirectToAction(nameof(Cart));
        }

        /// Cập nhật
        [Route("/updatecart", Name = "updatecart")]
        [HttpPost]
        public IActionResult UpdateCart([FromForm] int productid, [FromForm] int quantity) {
            // Cập nhật Cart thay đổi số lượng quantity ...
            var cart = GetCartItems();
            var cartitem = cart.Find(p => p.Product.ProductId == productid);
            if(cartitem != null) {
                // Đã tồn tại, tăng thêm 1
                cartitem.Quanlity = quantity;
            }
            SaveCartSession(cart);
            // Trả về mã thành công (không có nội dung gì - chỉ để Ajax gọi)
            return Ok();
        }

        // Hiện thị giỏ hàng
        [Route("/cart", Name = "cart")]
        public IActionResult Cart() {
            return View(GetCartItems());
        }

        [Route("/checkout")]
        public IActionResult CheckOut() {
            // Xử lý khi đặt hàng
            return View();
        }

        // GET: Products/Details/5
        public async Task<IActionResult> Details(int? id) {
            if(id == null) {
                return NotFound();
            }

            var product = await _context.Products
                .FirstOrDefaultAsync(m => m.ProductId == id);
            if(product == null) {
                return NotFound();
            }

            return View(product);
        }

        // GET: Products/Create
        public IActionResult Create() {
            return View();
        }

        // POST: Products/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("ProductId,Name,Description,Price")] Product product) {
            if(ModelState.IsValid) {
                _context.Add(product);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(product);
        }

        // GET: Products/Edit/5
        public async Task<IActionResult> Edit(int? id) {
            if(id == null) {
                return NotFound();
            }

            var product = await _context.Products.FindAsync(id);
            if(product == null) {
                return NotFound();
            }
            return View(product);
        }

        // POST: Products/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("ProductId,Name,Description,Price")] Product product) {
            if(id != product.ProductId) {
                return NotFound();
            }

            if(ModelState.IsValid) {
                try {
                    _context.Update(product);
                    await _context.SaveChangesAsync();
                } catch(DbUpdateConcurrencyException) {
                    if(!ProductExists(product.ProductId)) {
                        return NotFound();
                    } else {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(product);
        }

        // GET: Products/Delete/5
        public async Task<IActionResult> Delete(int? id) {
            if(id == null) {
                return NotFound();
            }

            var product = await _context.Products
                .FirstOrDefaultAsync(m => m.ProductId == id);
            if(product == null) {
                return NotFound();
            }

            return View(product);
        }

        // POST: Products/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id) {
            var product = await _context.Products.FindAsync(id);
            _context.Products.Remove(product);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool ProductExists(int id) {
            return _context.Products.Any(e => e.ProductId == id);
        }

        /// <summary>
        ///
        /// </summary>
        // Key lưu chuỗi json của Cart
        public const string CARTKEY = "cart";

        // Lấy cart từ Session (danh sách CartItem)
        private List<CartItem> GetCartItems() {
            var session = HttpContext.Session;
            string jsoncart = session.GetString(CARTKEY);
            if(jsoncart != null) {
                return JsonConvert.DeserializeObject<List<CartItem>>(jsoncart);
            }
            return new List<CartItem>();
        }

        // Xóa cart khỏi session
        private void ClearCart() {
            var session = HttpContext.Session;
            session.Remove(CARTKEY);
        }

        // Lưu Cart (Danh sách CartItem) vào session
        private void SaveCartSession(List<CartItem> ls) {
            var session = HttpContext.Session;
            string jsoncart = JsonConvert.SerializeObject(ls);
            session.SetString(CARTKEY, jsoncart);
        }

        /// Thêm sản phẩm vào cart
        [Route("addcart/{productid:int}", Name = "addcart")]
        public IActionResult AddToCart([FromRoute] int productid) {
            var product = _context.Products
                .Where(p => p.ProductId == productid)
                .FirstOrDefault();
            if(product == null)
                return NotFound("Không có sản phẩm");

            // Xử lý đưa vào Cart ...
            var cart = GetCartItems();
            var cartitem = cart.Find(p => p.Product.ProductId == productid);
            if(cartitem != null) {
                // Đã tồn tại, tăng thêm 1
                cartitem.Quanlity++;
            } else {
                //  Thêm mới
                cart.Add(new CartItem() { Quanlity = 1, Product = product });
            }

            // Lưu cart vào Session
            SaveCartSession(cart);
            // Chuyển đến trang hiện thị Cart
            return RedirectToAction(nameof(Cart));
        }
    }
}

Controllers/ViewPostController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.Caching.Memory;
using Microsoft.Extensions.Logging;
using XuanThuLab.Data;
using XuanThuLab.Models;

namespace XuanThuLab.Controllers {

    [Route("/posts")]
    public class ViewPostController : Controller {
        private readonly ILogger<ViewPostController> _logger;

        private readonly AppDbContext _context;

        private IMemoryCache _cache;

        // Số bài hiện thị viết trên một trang danh mục
        public const int ITEMS_PER_PAGE = 4;

        public ViewPostController(ILogger<ViewPostController> logger,
            AppDbContext context,
            IMemoryCache cache) {
            _logger = logger;
            _context = context;
            _cache = cache;
        }

        /// Lấy danh các Categories - có dùng cache
        [NonAction]
        private List<Category> GetCategories() {
            List<Category> categories;

            string keycacheCategories = "_listallcategories";

            // Phục hồi categories từ Memory cache, không có thì truy vấn Db
            if(!_cache.TryGetValue(keycacheCategories, out categories)) {
                categories = _context.Categories
                    .Include(c => c.CategoryChildren)
                    .AsEnumerable()
                    .Where(c => c.ParentCategory == null)
                    .ToList();

                // Thiết lập cache - lưu vào cache
                var cacheEntryOptions = new MemoryCacheEntryOptions()
                    .SetSlidingExpiration(TimeSpan.FromMinutes(300));
                _cache.Set("_GetCategories", categories, cacheEntryOptions);
            }

            return categories;
        }

        // Tìm (đệ quy) trong cây, một Category theo Slug
        [NonAction]
        private Category FindCategoryBySlug(List<Category> categories, string Slug) {
            foreach(var c in categories) {
                if(c.Slug == Slug)
                    return c;
                var c1 = FindCategoryBySlug(c.CategoryChildren.ToList(), Slug);
                if(c1 != null)
                    return c1;
            }

            return null;
        }

        [Route("{slug?}", Name = "listpost")]
        public async Task<IActionResult> Index([Bind(Prefix = "page")] int pageNumber, [FromRoute(Name = "slug")] string slugCategory) {
            var categories = GetCategories();

            Category category = null;
            if(!string.IsNullOrEmpty(slugCategory)) {
                category = FindCategoryBySlug(categories, slugCategory);
                if(category == null) {
                    return NotFound("Không thấy Category");
                }
            }
            ViewData["categories"] = categories;
            ViewData["slugCategory"] = slugCategory;
            ViewData["CurrentCategory"] = category;

            // Truy vấn lấy các post
            var posts = _context.Posts
                .Include(p => p.Author) // Load Author cho post
                .Include(p => p.PostCategories) // Load các Category của Post
                .ThenInclude(c => c.Category)
                .AsQueryable();

            if(category != null) {
                var ids = category.ChildCategoryIDs();
                ids.Add(category.Id);

                // Lọc các Post có trong category (và con của nó)
                posts = posts.Where(p => p.PostCategories
                   .Where(c => ids.Contains(c.CategoryID)).Any());
            }
            // Lấy tổng số dòng dữ liệu
            var totalItems = posts.Count();
            // Tính số trang hiện thị (mỗi trang hiện thị ITEMS_PER_PAGE mục)
            int totalPages = (int)Math.Ceiling((double)totalItems / ITEMS_PER_PAGE);
            if(totalPages < 1)
                totalPages = 1;
            if(pageNumber == 0)
                pageNumber = 1;

            if(pageNumber > totalPages) {
                var vals = new Dictionary<string, string>() { { "slug", slugCategory } };
                if(totalPages > 1)
                    vals["page"] = totalPages.ToString();
                return RedirectToRoute("listpost", vals);
            }

            // Chỉ lấy các Post trang hiện tại (theo pageNumber)
            posts = posts
                .Skip(ITEMS_PER_PAGE * (pageNumber - 1))
                .Take(ITEMS_PER_PAGE)
                .OrderByDescending(p => p.DateUpdated);

            ViewData["pageNumber"] = pageNumber;
            ViewData["totalPages"] = totalPages;

            // Thực hiện truy vấn lấy List các Post và chuyển cho View
            return View(await posts.ToListAsync());
        }

        [Route("{slug}.html", Name = "viewonepost")]
        public async Task<IActionResult> DisplayPost() {
            string Slug = (string)Request.RouteValues["slug"];

            if(string.IsNullOrEmpty(Slug)) {
                return NotFound("Không thấy trang");
            }

            // Truy vấn lấy bài viết theo Slug
            var post = await _context.Posts
                .Where(p => p.Slug == Slug)
                .Include(p => p.Author)
                .Include(p => p.PostCategories)
                .ThenInclude(c => c.Category)
                .FirstOrDefaultAsync();

            if(post == null) {
                return NotFound("Không thấy trang");
            }

            var categories = GetCategories();
            ViewData["categories"] = categories;

            return View(post);
        }
    }
}

Views/Shared/_AdminDropdownMenu.cshtml
@using Microsoft.AspNetCore.Identity
@using XuanThuLab.Models
@using Microsoft.AspNetCore.Authorization
@inject SignInManager<AppUser> SignInManager

@inject Microsoft.AspNetCore.Authorization.IAuthorizationService authorizationService
@if(SignInManager.IsSignedIn(User)
&& (await authorizationService.AuthorizeAsync(User, "AdminDropdown")).Succeeded) {
<li class="nav-item dropdown">
    <a class="nav-item nav-link dropdown-toggle mr-md-2" href="#" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
        Manager
    </a>
    <div class="dropdown-menu dropdown-menu-right" aria-labelledby="bd-versions">
        <a class="dropdown-item" asp-page="/Role/Index" asp-area="Admin">Quản lý role</a>

        <div class="dropdown-divider"></div>
        <a class="dropdown-item" asp-page="/Role/User" asp-area="Admin">Gán role cho User</a>
    </div>
</li>
}

Views/Shared/_CartPartial.cshtml
@using Microsoft.AspNetCore.Http
@using Newtonsoft.Json
@inject IHttpContextAccessor HttpContextAccessor

@{
    var session = HttpContextAccessor.HttpContext.Session;
    string jsoncart = session.GetString(XuanThuLab.Controllers.ProductsController.CARTKEY);
    if(jsoncart != null) {
        var cart = JsonConvert.DeserializeObject<List<CartItem>>(jsoncart);
        <div class="nav-item"><a asp-route="cart">Giỏ hàng(@cart.Count)</a></div>

    }
}

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - MyBlog</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">MyBlog</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">

                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="Admin" asp-controller="category" asp-action="Index">Category</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="Admin" asp-controller="post" asp-action="Index">Post</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="ViewPost" asp-action="Index">Posts</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Products" asp-action="Index">Products</a>
                        </li>
                    </ul>
                </div>
                @await Html.PartialAsync("_CartPartial")
                @await Html.PartialAsync("_LoginPartial")
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2021 - XuanThuLab - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

Views/Shared/_Paging.cshtml
@model dynamic
@{
    int currentPage = Model.currentPage;
    int countPages = Model.countPages;
    var generateUrl = Model.generateUrl;

    if(currentPage > countPages)
        currentPage = countPages;

    if(countPages <= 1)
        return;

    int? preview = null;
    int? next = null;

    if(currentPage > 1)
        preview = currentPage - 1;

    if(currentPage < countPages)
        next = currentPage + 1;

    // Các trang hiện thị trong điều hướng
    List<int> pagesRanges = new List<int>();

    int delta = 5;             // Số trang mở rộng về mỗi bên trang hiện tại
    int remain = delta * 2;      // Số trang hai bên trang hiện tại
    pagesRanges.Add(currentPage);
    // Các trang phát triển về hai bên trang hiện tại
    for(int i = 1; i <= delta; i++) {
        if(currentPage + i <= countPages) {
            pagesRanges.Add(currentPage + i);
            remain--;
        }

        if(currentPage - i >= 1) {
            pagesRanges.Insert(0, currentPage - i);
            remain--;
        }

    }
    // Xử lý thêm vào các trang cho đủ remain (xảy ra ở đầu mút của khoảng trang không đủ
    // trang chèn  vào)
    if(remain > 0) {
        if(pagesRanges[0] == 1) {
            for(int i = 1; i <= remain; i++) {
                if(pagesRanges.Last() + 1 <= countPages) {
                    pagesRanges.Add(pagesRanges.Last() + 1);
                }
            }
        } else {
            for(int i = 1; i <= remain; i++) {
                if(pagesRanges.First() - 1 > 1) {
                    pagesRanges.Insert(0, pagesRanges.First() - 1);
                }
            }
        }
    }

}

<ul class="pagination">
    <!-- Previous page link -->
    @if(preview != null) {
        <li class="page-item">
            <a class="page-link" href="@generateUrl(preview)">Trang trước</a>
        </li>
    } else {
        <li class="page-item disabled">
            <a class="page-link" href="#" tabindex="-1" aria-disabled="true">Trang trước</a>
        </li>
    }

    <!-- Numbered page links -->
    @foreach(var pageitem in pagesRanges) {
        if(pageitem != currentPage) {
            <li class="page-item">
                <a class="page-link" href="@generateUrl(pageitem)">
                    @pageitem
                </a>
            </li>
        } else {
            <li class="page-item active" aria-current="page">
                <a class="page-link" href="#">@pageitem <span class="sr-only">(current)</span></a>
            </li>
        }
    }

    <!-- Next page link -->
    @if(next != null) {
        <li class="page-item">
            <a class="page-link" href="@generateUrl(next)">Trang sau</a>
        </li>
    } else {
        <li class="page-item disabled">
            <a class="page-link" href="#" tabindex="-1" aria-disabled="true">Trang sau</a>
        </li>
    }
</ul>

Views/Shared/_PostLayout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - ToanBlog</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>

    <header>
        <nav class="navbar navbar-expand-sm
                    navbar-toggleable-sm navbar-dark bg-success
                    border-bottom box-shadow">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">ToanBlog</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse"
                        data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>

                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">

                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="Admin" asp-controller="category" asp-action="Index">Category</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="Admin" asp-controller="post" asp-action="Index">Post</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="ViewPost" asp-action="Index">Posts</a>
                        </li>
                    </ul>
                </div>
                @await Html.PartialAsync("_LoginPartial")
            </div>
        </nav>
    </header>

    <div class="container">
        <div class="row">
            <main role="main" class="col-8 pb-3">
                @RenderBody()
            </main>
            <div class="col-4 pb-3">
                @RenderSection("Sidebar", false)
            </div>
        </div>
    </div>

    <footer class="border-top footer text-muted bg-warning">
        <div class="container">
            &copy; 2020 - mvcblog - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>

Views/Shared/_Summernote.cshtml
@model dynamic
@{
    int height = Model.height ?? 200;
    string selector = Model.selector;
}

<link rel="stylesheet" href="~/lib2/jqueryui/themes/base/theme.css" />
<link rel="stylesheet" href="~/lib2/jqueryui/themes/base/jquery-ui.css" />
<link rel="stylesheet" href="~/lib2/elfinder/css/elfinder.full.css" />
<link rel="stylesheet" href="~/lib2/elfinder/css/theme.min.css" />
<link rel="stylesheet" href="~/css/elfinder-material-theme/Material/css/theme-gray.css" />
<script src="~/lib2/jqueryui/jquery-ui.min.js"></script>
<script src="~/lib2/elfinder/js/elfinder.min.js"></script>

<script src="@Url.Content("~/summernote/dist/summernote-bs4.js")"></script>
<link href="@Url.Content("~/summernote/dist/summernote-bs4.min.css")" rel="stylesheet">

<script>
    (function (factory) {
        if (typeof define === 'function' && define.amd) {
            define(['jquery'], factory);
        }
        else if (typeof module === 'object' && module.exports) {
            module.exports = factory(require('jquery'));
        } else {
            factory(window.jQuery);
        }
    }(function ($) {
      $.extend($.summernote.plugins, {
            // Tạo plugin tên elfinder
            'elfinder': function (context) {
                var self = this;
                // ui has renders to build ui elements.
                var ui = $.summernote.ui;
                // Tạo nút bấm
                context.memo('button.elfinder', function () {
                    var button = ui.button({
                        contents: '<i class="note-icon-picture" /> elFinder',
                        tooltip: 'Quản lý file',
                        click: function () {
                            // Bấm vào nút bấm gọi hàm elfinderDialog
                            elfinderDialog(context);
                        }
                    });
                    // create jQuery object from button instance.
                    var $elfinder = button.render();
                    return $elfinder;
                });
                // This methods will be called when editor is destroyed by $('..').summernote('destroy');
                // You should remove elements on `initialize`.
                this.destroy = function () {
                    this.$panel.remove();
                    this.$panel = null;
                };
            }

        });
    }));

function elfinderDialog(editor) {
  	    var fm = $('<div />').dialogelfinder({
  		url : '/el-finder-file-system/connector', // change with the url of your connector
        baseUrl: "/lib2/elfinder/",
  		lang : 'vi',
  		width : 840,
  		height: 450,
  		destroyOnClose : true,
  		getFileCallback : function(files, fm) {
  			console.log(files);
            editor.invoke('editor.insertImage', files.url);
  		},
  		commandsOptions : {
  			getfile : {
  			    oncomplete : 'close',
  			    folders : false
  			}
  		}
  	}).dialogelfinder('instance');
}

$(document).ready(function() {
        $('@selector').summernote({
            height: @height,
            toolbar: [
                // [groupName, [list of button]]
                    ['style', ['style']],
                    ['font', ['bold', 'underline', 'clear']],
                    ['fontname', ['fontname']],
                    ['color', ['color']],
                    ['para', ['ul', 'ol', 'paragraph']],
                    ['table', ['table']],
                    ['insert', ['link', 'picture', 'video', 'elfinder']],
                    ['view', ['fullscreen', 'codeview', 'help']],
                ],
        });
    });
</script>