Areas/Admin/Controllers/CategoryController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using XuanThuLab.Data;
using XuanThuLab.Models;

namespace XuanThuLab.Areas.Admin.Blog.Controllers {

    [Area("Admin")]
    [Authorize]
    public class CategoryController : Controller {
        private readonly AppDbContext _context;

        public CategoryController(AppDbContext context) {
            _context = context;
        }

        // GET: Admin/Category
        public IActionResult Index() {
            var items = _context.Categories
                .Include(c => c.CategoryChildren)   // <-- Nạp các Category con
                .AsEnumerable()
                .Where(c => c.ParentCategory == null)
                .ToList();

            return View(items);
        }

        // GET: Admin/Category/Details/5
        public async Task<IActionResult> Details(int? id) {
            if(id == null) {
                return NotFound();
            }

            var category = await _context.Categories
                .Include(c => c.ParentCategory)
                .FirstOrDefaultAsync(m => m.Id == id);
            if(category == null) {
                return NotFound();
            }

            return View(category);
        }

        // GET: Admin/Category/Create
        public async Task<IActionResult> Create() {
            // ViewData["ParentId"] = new SelectList(_context.Categories, "Id", "Slug");
            var listcategory = await _context.Categories.ToListAsync();
            listcategory.Insert(0, new Category() {
                Title = "Không có danh mục cha",
                Id = -1
            });
            ViewData["ParentId"] = new SelectList(await GetItemsSelectCategorie(), "Id", "Title", -1);
            return View();
        }

        private async Task<IEnumerable<Category>> GetItemsSelectCategorie() {
            var items = await _context.Categories
                                .Include(c => c.CategoryChildren)
                                .Where(c => c.ParentCategory == null)
                                .ToListAsync();

            List<Category> resultitems = new List<Category>() {
                new Category() {
                    Id = -1,
                    Title = "Không có danh mục cha"
                }
            };
            Action<List<Category>, int> _ChangeTitleCategory = null;
            Action<List<Category>, int> ChangeTitleCategory = (items, level) => {
                string prefix = String.Concat(Enumerable.Repeat("—", level));
                foreach(var item in items) {
                    item.Title = prefix + " " + item.Title;
                    resultitems.Add(item);
                    if((item.CategoryChildren != null) && (item.CategoryChildren.Count > 0)) {
                        _ChangeTitleCategory(item.CategoryChildren.ToList(), level + 1);
                    }
                }
            };

            _ChangeTitleCategory = ChangeTitleCategory;
            ChangeTitleCategory(items, 0);

            return resultitems;
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,ParentId,Title,Content,Slug")] Category category) {
            if(ModelState.IsValid) {
                if(category.ParentId.Value == -1)
                    category.ParentId = null;
                _context.Add(category);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }

            // ViewData["ParentId"] = new SelectList(_context.Categories, "Id", "Slug", category.ParentId);
            var listcategory = await _context.Categories.ToListAsync();
            listcategory.Insert(0, new Category() {
                Title = "Không có danh mục cha",
                Id = -1
            });
            ViewData["ParentId"] = new SelectList(await GetItemsSelectCategorie(), "Id", "Title", category.ParentId);
            return View(category);
        }

        // GET: Admin/Category/Edit/5
        public async Task<IActionResult> Edit(int? id) {
            if(id == null) {
                return NotFound();
            }

            var category = await _context.Categories.FindAsync(id);
            if(category == null) {
                return NotFound();
            }

            ViewData["ParentId"] = new SelectList(await GetItemsSelectCategorie(), "Id", "Title", category.ParentId);

            return View(category);
        }

        // POST: Admin/Category/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,ParentId,Title,Content,Slug")] Category category) {
            if(id != category.Id) {
                return NotFound();
            }

            if(ModelState.IsValid) {
                try {
                    if(category.ParentId == -1) {
                        category.ParentId = null;
                    }
                    _context.Update(category);
                    await _context.SaveChangesAsync();
                } catch(DbUpdateConcurrencyException) {
                    if(!CategoryExists(category.Id)) {
                        return NotFound();
                    } else {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            var listcategory = await _context.Categories.ToListAsync();
            listcategory.Insert(0, new Category() {
                Title = "Không có danh mục cha",
                Id = -1
            });
            ViewData["ParentId"] = new SelectList(listcategory, "Id", "Title", category.ParentId);
            return View(category);
        }

        // GET: Admin/Category/Delete/5
        public async Task<IActionResult> Delete(int? id) {
            if(id == null) {
                return NotFound();
            }

            var category = await _context.Categories
                .Include(c => c.ParentCategory)
                .FirstOrDefaultAsync(m => m.Id == id);
            if(category == null) {
                return NotFound();
            }

            return View(category);
        }

        // POST: Admin/Category/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id) {
            var category = await _context.Categories.FindAsync(id);
            _context.Categories.Remove(category);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool CategoryExists(int id) {
            return _context.Categories.Any(e => e.Id == id);
        }
    }
}

Areas/Admin/Controllers/PostController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using XuanThuLab.core;
using XuanThuLab.Data;
using XuanThuLab.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.ModelBinding;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.Logging;

namespace XuanThuLab.Areas.Admin.Controllers {

    [Area("Admin")]
    [Authorize]
    public class PostController : Controller {
        private readonly AppDbContext _context;

        private readonly UserManager<AppUser> _usermanager;

        private readonly ILogger<PostController> _logger;

        public PostController(AppDbContext context,
            UserManager<AppUser> usermanager,
            ILogger<PostController> logger) {
            _context = context;
            _usermanager = usermanager;
            _logger = logger;
        }

        public const int ITEMS_PER_PAGE = 4;

        // GET: Admin/Post
        public async Task<IActionResult> Index([Bind(Prefix = "page")] int pageNumber) {
            if(pageNumber == 0)
                pageNumber = 1;

            var listPosts = _context.Posts
                .Include(p => p.Author)
                .Include(p => p.PostCategories)
                .ThenInclude(c => c.Category)
                .OrderByDescending(p => p.DateCreated);

            _logger.LogInformation(pageNumber.ToString());

            // Lấy tổng số dòng dữ liệu
            var totalItems = listPosts.Count();
            // Tính số trang hiện thị (mỗi trang hiện thị ITEMS_PER_PAGE mục)
            int totalPages = (int)Math.Ceiling((double)totalItems / ITEMS_PER_PAGE);

            if(pageNumber > totalPages)
                return RedirectToAction(nameof(PostController.Index), new { page = totalPages });

            var posts = await listPosts
                .Skip(ITEMS_PER_PAGE * (pageNumber - 1))
                .Take(ITEMS_PER_PAGE)
                .ToListAsync();

            // return View (await listPosts.ToListAsync());
            ViewData["pageNumber"] = pageNumber;
            ViewData["totalPages"] = totalPages;

            return View(posts.AsEnumerable());
        }

        // GET: Admin/Post/Details/5
        public async Task<IActionResult> Details(int? id) {
            if(id == null) {
                return NotFound();
            }

            var post = await _context.Posts
                .Include(p => p.Author)
                .FirstOrDefaultAsync(m => m.PostId == id);
            if(post == null) {
                return NotFound();
            }

            return View(post);
        }

        [BindProperty]
        public int[] selectedCategories { set; get; }

        // GET: Admin/Post/Create
        public async Task<IActionResult> Create() {
            // Thông tin về User tạo Post
            var user = await _usermanager.GetUserAsync(User);
            ViewData["userpost"] = $"{user.UserName} {user.FullName}";

            // Danh mục chọn để đăng bài Post, tạo MultiSelectList
            var categories = await _context.Categories.ToListAsync();
            ViewData["categories"] = new MultiSelectList(categories, "Id", "Title");
            return View();
        }

        // POST: Admin/Post/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("PostId,Title,Description,Slug,Content,Published")] PostBase post) {
            var user = await _usermanager.GetUserAsync(User);
            ViewData["userpost"] = $"{user.UserName} {user.FullName}";

            // Phát sinh Slug theo Title
            if(ModelState["Slug"].ValidationState == ModelValidationState.Invalid) {
                post.Slug = Utils.GenerateSlug(post.Title);
                ModelState.SetModelValue("Slug", new ValueProviderResult(post.Slug));
                // Thiết lập và kiểm tra lại Model
                ModelState.Clear();
                TryValidateModel(post);
            }

            if(selectedCategories.Length == 0) {
                ModelState.AddModelError(String.Empty, "Phải ít nhất một chuyên mục");
            }

            bool SlugExisted = await _context.Posts.Where(p => p.Slug == post.Slug).AnyAsync();
            if(SlugExisted) {
                ModelState.AddModelError(nameof(post.Slug), "Slug đã có trong Database");
            }

            if(ModelState.IsValid) {
                //Tạo Post
                var newpost = new Post() {
                    AuthorId = user.Id,
                    Title = post.Title,
                    Slug = post.Slug,
                    Content = post.Content,
                    Description = post.Description,
                    Published = post.Published,
                    DateCreated = DateTime.Now,
                    DateUpdated = DateTime.Now
                };
                _context.Add(newpost);
                await _context.SaveChangesAsync();

                // Chèn thông tin về PostCategory của bài Post
                foreach(var selectedCategory in selectedCategories) {
                    _context.Add(new PostCategory() { PostID = newpost.PostId, CategoryID = selectedCategory });
                }
                await _context.SaveChangesAsync();

                return RedirectToAction(nameof(Index));
            }

            var categories = await _context.Categories.ToListAsync();
            ViewData["categories"] = new MultiSelectList(categories, "Id", "Title", selectedCategories);
            return View(post);
        }

        // GET: Admin/Post/Edit/5
        public async Task<IActionResult> Edit(int? id) {
            if(id == null) {
                return NotFound();
            }

            // var post = await _context.Posts.FindAsync (id);
            var post = await _context.Posts.Where(p => p.PostId == id)
                .Include(p => p.Author)
                .Include(p => p.PostCategories)
                .ThenInclude(c => c.Category).FirstOrDefaultAsync();
            if(post == null) {
                return NotFound();
            }

            ViewData["userpost"] = $"{post.Author.UserName} {post.Author.FullName}";
            ViewData["datecreate"] = post.DateCreated.ToShortDateString();

            // Danh mục chọn
            var selectedCates = post.PostCategories.Select(c => c.CategoryID).ToArray();
            var categories = await _context.Categories.ToListAsync();
            ViewData["categories"] = new MultiSelectList(categories, "Id", "Title", selectedCates);

            return View(post);
        }

        // POST: Admin/Post/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("PostId,Title,Description,Slug,Content,Published")] PostBase post) {
            if(id != post.PostId) {
                return NotFound();
            }

            // Phát sinh Slug theo Title
            if(ModelState["Slug"].ValidationState == ModelValidationState.Invalid) {
                post.Slug = Utils.GenerateSlug(post.Title);
                ModelState.SetModelValue("Slug", new ValueProviderResult(post.Slug));
                // Thiết lập và kiểm tra lại Model
                ModelState.Clear();
                TryValidateModel(post);
            }

            if(selectedCategories.Length == 0) {
                ModelState.AddModelError(String.Empty, "Phải ít nhất một chuyên mục");
            }

            bool SlugExisted = await _context.Posts.Where(p => p.Slug == post.Slug && p.PostId != post.PostId).AnyAsync();
            if(SlugExisted) {
                ModelState.AddModelError(nameof(post.Slug), "Slug đã có trong Database");
            }

            if(ModelState.IsValid) {
                // Lấy nội dung từ DB
                var postUpdate = await _context.Posts.Where(p => p.PostId == id)
                    .Include(p => p.PostCategories)
                    .ThenInclude(c => c.Category).FirstOrDefaultAsync();
                if(postUpdate == null) {
                    return NotFound();
                }

                // Cập nhật nội dung mới
                postUpdate.Title = post.Title;
                postUpdate.Description = post.Description;
                postUpdate.Content = post.Content;
                postUpdate.Slug = post.Slug;
                postUpdate.DateUpdated = DateTime.Now;
                postUpdate.Published = post.Published;

                // Các danh mục không có trong selectedCategories
                var listcateremove = postUpdate.PostCategories
                                               .Where(p => !selectedCategories.Contains(p.CategoryID))
                                               .ToList();
                listcateremove.ForEach(c => postUpdate.PostCategories.Remove(c));

                // Các ID category chưa có trong postUpdate.PostCategories
                var listCateAdd = selectedCategories
                                    .Where(
                                        id => !postUpdate.PostCategories.Where(c => c.CategoryID == id).Any()
                                    ).ToList();

                listCateAdd.ForEach(id => {
                    postUpdate.PostCategories.Add(new PostCategory() {
                        PostID = postUpdate.PostId,
                        CategoryID = id
                    });
                });

                try {
                    _context.Update(postUpdate);

                    await _context.SaveChangesAsync();
                } catch(DbUpdateConcurrencyException) {
                    if(!PostExists(post.PostId)) {
                        return NotFound();
                    } else {

Areas/Admin/Views/Category/Create.cshtml
@model XuanThuLab.Models.Category

@{
    ViewData["Title"] = "DANH MỤC";
    Layout = "_Layout";
}

<h1>@ViewBag.Title</h1>

<h4>Tạo danh mục Blog</h4>
<hr />
<div class="row">
    <div class="col-md-8">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="ParentId" class="control-label"></label>
                <select asp-for="ParentId" class="form-control" asp-items="ViewBag.ParentId"></select>
            </div>
            <div class="form-group">
                <label asp-for="Title" class="control-label"></label>
                <input asp-for="Title" class="form-control" />
                <span asp-validation-for="Title" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Content" class="control-label"></label>
                <input asp-for="Content" class="form-control" />
                <span asp-validation-for="Content" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Slug" class="control-label"></label>
                <input asp-for="Slug" class="form-control" />
                <span asp-validation-for="Slug" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Tạo mới" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Quay lại danh sách</a>
</div>

@section Scripts
{
    @await Html.PartialAsync("_Summernote", new { height = 200, selector = "#Content" })
}

Areas/Admin/Views/Category/Delete.cshtml
@model XuanThuLab.Models.Category

@{
    ViewData["Title"] = "Delete";
    Layout = "_Layout";
}

<h1>Xóa danh mục</h1>

<h3>Có chắc chắn xóa danh mục?</h3>
<div>
    <hr />
    <dl class="row">
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Title)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Title)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Content)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Content)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Slug)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Slug)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.ParentCategory)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.ParentCategory.Title)
        </dd>
    </dl>

    <form asp-action="Delete">
        <input type="hidden" asp-for="Id" />
        <input type="submit" value="Xóa" class="btn btn-danger" /> |
        <a asp-action="Index">Quay lại danh sách</a>
    </form>
</div>

Areas/Admin/Views/Category/Details.cshtml
@model XuanThuLab.Models.Category

@{
    ViewData["Title"] = "Details";
    Layout = "_Layout";
}

<h1>Details</h1>

<div>
    <h4>Category</h4>
    <hr />
    <dl class="row">
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Title)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Title)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Content)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Content)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Slug)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Slug)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.ParentCategory)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.ParentCategory.Slug)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model.Id">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>

Areas/Admin/Views/Category/Edit.cshtml
@model XuanThuLab.Models.Category

@{
    ViewData["Title"] = "Edit";
    Layout = "_Layout";
}

<h1>Edit</h1>

<h4>Blog Category</h4>
<hr />
<div class="row">
    <div class="col-md-8">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="Id" />
            <div class="form-group">
                <label asp-for="ParentId" class="control-label"></label>
                <select asp-for="ParentId" class="form-control" asp-items="ViewBag.ParentId"></select>
                <span asp-validation-for="ParentId" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Title" class="control-label"></label>
                <input asp-for="Title" class="form-control" />
                <span asp-validation-for="Title" class="text-danger"></span>
            </div>
            <!--Sử dụng textarea nhập dữ liệu cho Content-->
            <div class="form-group">
                <label asp-for="Content" class="control-label"></label>
                <textarea asp-for="Content" class="form-control"></textarea>
                <span asp-validation-for="Content" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Slug" class="control-label"></label>
                <input asp-for="Slug" class="form-control" />
                <span asp-validation-for="Slug" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Lưu lại" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Quay lại danh sách</a>
</div>

@section Scripts
{
    @await Html.PartialAsync("_Summernote", new { height = 200, selector = "#Content" })
}

Areas/Admin/Views/Category/Index.cshtml
@model IEnumerable<XuanThuLab.Models.Category>

@{
    ViewData["Title"] = "Danh sách các chuyên mục Blog";
    Layout = "_Layout";
}

<h1>@ViewData["Title"]</h1>

<p>
    <a asp-action="Create">Tạo chuyên mục mới</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Title)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Slug)
            </th>

            <th></th>
        </tr>
    </thead>
    <tbody>

        @if(Model.Count() > 0)
            @await Component.InvokeAsync("RowTreeCategory", new { categories = Model, level = 0 })
    </tbody>
</table>

Areas/Admin/Views/Category/_Layout.cshtml
@{
    Layout = "/Views/Shared/Admin/_Layout.cshtml";
}

@RenderBody()

@section TopBar {
    @await Html.PartialAsync("/Views/Shared/Admin/_TopBar.cshtml")
}

@section SideBar {
    <partial name="/Areas/Admin/Views/Post/_SideBar.cshtml" />
}

@section Scripts {
    @RenderSection("Scripts", required: false)
}

Areas/Admin/Views/Category/_SideBar.cshtml
@using Microsoft.AspNetCore.Identity
@using XuanThuLab.Models
@inject SignInManager<AppUser> SignInManager
@{
    var hasExternalLogins = (await SignInManager.GetExternalAuthenticationSchemesAsync()).Any();
    string activePage = System.IO.Path.GetFileNameWithoutExtension(ViewContext.ActionDescriptor.DisplayName);
    Func<string, string, string> ActiveClass = (string activePage, string page) => {
        return (activePage == page) ? "active" : "";
    };
}
<ul class="navbar-nav bg-gradient-primary sidebar sidebar-dark accordion" id="accordionSidebar">

    <!-- Sidebar - Brand -->
    <a class="sidebar-brand d-flex align-items-center justify-content-center"
       asp-action="Index" asp-controller="Home" asp-area="">
        <div class="sidebar-brand-icon rotate-n-15">
            <i class="fas fa-laugh-wink"></i>
        </div>
        <div class="sidebar-brand-text mx-3">ToanDang</div>
    </a>

    <!-- Divider -->
    <hr class="sidebar-divider my-0">

    <!-- Heading -->
    <div class="sidebar-heading mt-2">
        Quản lý tài khoản
    </div>

    <!-- Nav Item - Pages Collapse Menu -->
    <li class="nav-item">
        <a class="nav-link collapsed" href="#" data-toggle="collapse" data-target="#collapseUserManage" aria-expanded="true" aria-controls="collapseTwo">
            <i class="fas fa-fw fa-cog"></i>
            <span>Tài khoản cá nhân</span>
        </a>
        <div id="collapseUserManage" class="collapse" aria-labelledby="headingTwo" data-parent="#accordionSidebar">
            <div class="bg-white py-2 collapse-inner rounded">
                <h6 class="collapse-header">Chức năng</h6>
                <a class="collapse-item" asp-area="Identity" asp-page="/Account/Manage/Index">Profile</a>
                <a class="collapse-item" asp-area="Identity" asp-page="/Account/Manage/Email">Email</a>
                <a class="collapse-item" asp-area="Identity" asp-page="/Account/Manage/ChangePassword">Password</a>
                @if(hasExternalLogins) {
                    <a class="collapse-item" asp-page="/Account/Manage/ExternalLogins">External logins</a>
                }
                <a class="collapse-item" asp-area="Identity" asp-page="/Account/Manage/TwoFactorAuthentication">Two-factor authentication</a>
                <a class="collapse-item" asp-area="Identity" asp-page="/Account/Manage/PersonalData">Personal data</a>
            </div>
        </div>
    </li>
    <!-- Nav Item - Pages Collapse Menu -->
    <li class="nav-item">
        <a class="nav-link collapsed" href="#" data-toggle="collapse" data-target="#collapsePhanquyen" aria-expanded="true" aria-controls="collapseTwo">
            <i class="fas fa-user-cog"></i>
            <span>Phân quyền</span>
        </a>
        <div id="collapsePhanquyen" class="collapse" aria-labelledby="headingTwo" data-parent="#accordionSidebar">
            <div class="bg-white py-2 collapse-inner rounded">
                <a class="collapse-item @ActiveClass(activePage, "Index")" asp-page="/Role/Index" asp-area="Admin">Các Role - Vai trò</a>
                <a class="collapse-item @ActiveClass(activePage, "User")" asp-page="/Role/User" asp-area="Admin">Gán vai trò (phân quyền)</a>
            </div>
        </div>
    </li>

    <!-- Divider -->
    <hr class="sidebar-divider d-none d-md-block">

    <!-- Heading -->
    <div class="sidebar-heading mt-2">
        Posts
    </div>
    <!-- Nav Item - Pages Collapse Menu -->
    <li class="nav-item">
        <a class="nav-link collapsed" href="#" data-toggle="collapse" data-target="#collapsePosts" aria-expanded="true" aria-controls="collapseTwo">
            <i class="fas fa-newspaper"></i>
            <span>QL Bài viết</span>
        </a>
        <div id="collapsePosts" class="collapse show" aria-labelledby="headingTwo" data-parent="#accordionSidebar">
            <div class="bg-white py-2 collapse-inner rounded">
                <a class="collapse-item active" asp-controller="Category" asp-area="Admin"><i class="fas fa-list"></i> Danh mục Blog</a>
                <a class="collapse-item" asp-controller="Post" asp-area="Admin" asp-action="Index"><i class="fas fa-list"></i> Danh sách bài viết</a>
                <a class="collapse-item" asp-controller="Post" asp-area="Admin" asp-action="Create"><i class="fas fa-plus-circle"></i> Thêm bài viết</a>
            </div>
        </div>
    </li>

    <!-- Divider -->
    <hr class="sidebar-divider d-none d-md-block">

    <!-- Sidebar Toggler (Sidebar) -->
    <div class="text-center d-none d-md-inline">
        <button class="rounded-circle border-0" id="sidebarToggle"></button>
    </div>
</ul>
<!-- End of Sidebar -->